<?php
// Clients, adresses, réservations et suivi d'exécution.
return [
"CREATE TABLE customers (id {{PK}}, company_id INT NOT NULL DEFAULT 1, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, phone VARCHAR(20) NOT NULL,
  email VARCHAR(190) NULL, notes TEXT NULL, created_at DATETIME NOT NULL, deleted_at DATETIME NULL) {{ENGINE}}",
"CREATE UNIQUE INDEX uq_customers_phone ON customers (company_id, phone)",
"CREATE TABLE customer_addresses (id {{PK}}, customer_id INT NOT NULL, neighborhood_id INT NULL, address_text TEXT NOT NULL, instructions TEXT NULL,
  created_at DATETIME NOT NULL, deleted_at DATETIME NULL, FOREIGN KEY (customer_id) REFERENCES customers(id)) {{ENGINE}}",
"CREATE TABLE bookings (id {{PK}}, company_id INT NOT NULL DEFAULT 1, reference VARCHAR(30) NOT NULL UNIQUE, customer_id INT NOT NULL, address_id INT NULL,
  neighborhood_id INT NOT NULL, service_id INT NOT NULL, address_text TEXT NOT NULL, instructions TEXT NULL,
  scheduled_date DATE NOT NULL, start_time VARCHAR(5) NOT NULL, end_time VARCHAR(5) NOT NULL, duration_minutes INT NOT NULL,
  team_id INT NULL, status VARCHAR(20) NOT NULL DEFAULT 'pending', subtotal INT NOT NULL DEFAULT 0, travel_fee INT NOT NULL DEFAULT 0, total INT NOT NULL DEFAULT 0,
  declared_amount INT NULL, payment_note VARCHAR(255) NULL, internal_notes TEXT NULL, cancel_reason VARCHAR(255) NULL, reminder_sent_at DATETIME NULL,
  source VARCHAR(20) NOT NULL DEFAULT 'web', created_at DATETIME NOT NULL, updated_at DATETIME NULL,
  FOREIGN KEY (customer_id) REFERENCES customers(id), FOREIGN KEY (service_id) REFERENCES services(id), FOREIGN KEY (neighborhood_id) REFERENCES neighborhoods(id)) {{ENGINE}}",
"CREATE INDEX idx_bookings_day_team ON bookings (scheduled_date, team_id)",
"CREATE INDEX idx_bookings_status ON bookings (status)",
"CREATE INDEX idx_bookings_customer ON bookings (customer_id)",
"CREATE TABLE booking_items (id {{PK}}, booking_id INT NOT NULL, service_id INT NOT NULL, name VARCHAR(190) NOT NULL, formula_name VARCHAR(120) NULL, details TEXT NULL,
  quantity INT NOT NULL DEFAULT 1, unit_price INT NOT NULL DEFAULT 0, total INT NOT NULL DEFAULT 0, duration_minutes INT NOT NULL DEFAULT 0,
  FOREIGN KEY (booking_id) REFERENCES bookings(id) ON DELETE CASCADE) {{ENGINE}}",
"CREATE TABLE booking_assignments (id {{PK}}, booking_id INT NOT NULL, team_id INT NOT NULL, staff_id INT NULL, assigned_by INT NULL, active TINYINT NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL, FOREIGN KEY (booking_id) REFERENCES bookings(id) ON DELETE CASCADE) {{ENGINE}}",
"CREATE TABLE booking_status_history (id {{PK}}, booking_id INT NOT NULL, from_status VARCHAR(20) NULL, to_status VARCHAR(20) NOT NULL, user_id INT NULL, note VARCHAR(255) NULL,
  created_at DATETIME NOT NULL, FOREIGN KEY (booking_id) REFERENCES bookings(id) ON DELETE CASCADE) {{ENGINE}}",
"CREATE TABLE booking_notes (id {{PK}}, booking_id INT NOT NULL, user_id INT NULL, note TEXT NOT NULL, created_at DATETIME NOT NULL,
  FOREIGN KEY (booking_id) REFERENCES bookings(id) ON DELETE CASCADE) {{ENGINE}}",
"CREATE TABLE booking_photos (id {{PK}}, booking_id INT NOT NULL, user_id INT NULL, kind VARCHAR(10) NOT NULL, path VARCHAR(190) NOT NULL, created_at DATETIME NOT NULL,
  FOREIGN KEY (booking_id) REFERENCES bookings(id) ON DELETE CASCADE) {{ENGINE}}",
"CREATE TABLE route_plans (id {{PK}}, company_id INT NOT NULL DEFAULT 1, team_id INT NOT NULL, plan_date DATE NOT NULL, created_at DATETIME NOT NULL) {{ENGINE}}",
"CREATE TABLE route_stops (id {{PK}}, route_plan_id INT NOT NULL, booking_id INT NOT NULL, position INT NOT NULL, eta VARCHAR(5) NULL,
  FOREIGN KEY (route_plan_id) REFERENCES route_plans(id) ON DELETE CASCADE) {{ENGINE}}",
];
